name: Java CI with Gradle
on: [push, pull_request]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ["1.7", "1.8.9", "1.9.4", "1.10.2", "1.11.2", "1.12.2", "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.19.2", "22w19a", "1.20"]

    name: Build ${{ matrix.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate ${{ matrix.version }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :${{ matrix.version }}:runServer

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: data-${{ matrix.version }}
          path: ${{ matrix.version }}/run/minecraft-data
          if-no-files-found: error
